Fix equality operator arguments
...which avoids overload resolution ambiguities in C++20, when a synthesized
candidate of operator == for a reversed-argument rewrite conflicts with the
actual operator ==, as one is a template specialization for int and the other
for float.  (As observed with recent Clang 10 trunk with -std=c++2a when
building libstaroffice as part of LibreOffice:

> STOFFChart.cxx:230:63: error: use of overloaded operator '==' is ambiguous (with operand types 'STOFFVec2f' (aka 'STOFFVec2<float>') and 'STOFFVec2i' (aka 'STOFFVec2<int>'))
>     bool autoPlace=m_legendPosition==STOFFBox2f()||m_dimension==STOFFVec2i();
>                                                    ~~~~~~~~~~~^ ~~~~~~~~~~~~
> ./libstaroffice_internal.hxx:687:8: note: candidate function
>   bool operator==(STOFFVec2<T> const &p) const
>        ^
> ./libstaroffice_internal.hxx:687:8: note: candidate function (with reversed parameter order)
> STOFFChart.cxx:270:63: error: use of overloaded operator '==' is ambiguous (with operand types 'STOFFVec2f' (aka 'STOFFVec2<float>') and 'STOFFVec2i' (aka 'STOFFVec2<int>'))
>   bool autoPlace=m_plotAreaPosition==STOFFBox2f()||m_dimension==STOFFVec2i();
>                                                    ~~~~~~~~~~~^ ~~~~~~~~~~~~
> ./libstaroffice_internal.hxx:687:8: note: candidate function
>   bool operator==(STOFFVec2<T> const &p) const
>        ^
> ./libstaroffice_internal.hxx:687:8: note: candidate function (with reversed parameter order)

)